.PHONY: clean All

All:
	@echo "----------Building project:[ lab1_1 - Debug ]----------"
	@cd "lab1_1" && "$(MAKE)" -f  "lab1_1.mk"
clean:
	@echo "----------Cleaning project:[ lab1_1 - Debug ]----------"
	@cd "lab1_1" && "$(MAKE)" -f  "lab1_1.mk" clean
